# Generated by Django 2.2.9 on 2022-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220326_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Укажите уникальную ссылку (на английском) для группы', max_length=30, unique=True, verbose_name='Ссылка'),
        ),
    ]
